config/routes.rb
Theverb::Application.routes.draw do
  resources :posts

  resources :homespaces

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  
  get "/auth/:provider/callback" => "sessions#create"
  
  resources :users
  
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/signup" => "devise/registrations#new"
    delete "/logout" => "devise/sessions#destroy"
  end
  
  

  
    authenticated :user do
      root :to => redirect("/posts"), :as => "authenticated_root"
    end
    
    root :to => redirect("/users")

  

end

app/models/homespace.rb
class Homespace < ActiveRecord::Base
    belongs_to :user
    belongs_to :partner, class_name: "User", foreign_key: "partner_id"
    has_many :posts
    

end

app/controllers/homespaces_controller.rb
class HomespacesController < ApplicationController
  before_action :set_homespace, only: [:show, :edit, :update, :destroy]

  # GET /homespaces
  # GET /homespaces.json
  def index
    @homespaces = Homespace.all
  end

  # GET /homespaces/1
  # GET /homespaces/1.json
  def show
  end

  # GET /homespaces/new
  def new
    @homespace = Homespace.new
  end

  # GET /homespaces/1/edit
  def edit
  end

  # POST /homespaces
  # POST /homespaces.json
  def create
    @homespace = Homespace.new(homespace_params)

    respond_to do |format|
      if @homespace.save
        format.html { redirect_to @homespace, notice: 'Homespace was successfully created.' }
        format.json { render action: 'show', status: :created, location: @homespace }
      else
        format.html { render action: 'new' }
        format.json { render json: @homespace.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /homespaces/1
  # PATCH/PUT /homespaces/1.json
  def update
    respond_to do |format|
      if @homespace.update(homespace_params)
        format.html { redirect_to @homespace, notice: 'Homespace was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @homespace.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /homespaces/1
  # DELETE /homespaces/1.json
  def destroy
    @homespace.destroy
    respond_to do |format|
      format.html { redirect_to homespaces_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_homespace
      @homespace = Homespace.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def homespace_params
      params.require(:homespace).permit(:user_id, :partner_id, :post_ids, :title)
    end
end

app/helpers/homespaces_helper.rb
module HomespacesHelper
end

app/views/homespaces/_form.html.erb
<%= simple_form_for @homespace do |f| %>
    <%= f.input :title %><br />
    <p>(We suggest something like <%= [current_user.username, "and", current_user.partner.username].join("-").downcase %>)</p>
    <% unless @homespace.user_id %>
        <%= f.association :user_id, :as => :hidden, :input_html => { :value => current_user.id } %>
    <% end %>
    <% unless @homespace.partner_id %>
        <% if current_user.partner %>
            <%= f.association :partner_id, :as => :hidden, :input_html => { :value => current_user.partner.id } %>
        <% end %>
    <% end %>
    <%= f.button :submit, :class => 'blue_button' %>
<% end %>

app/views/homespaces/edit.html.erb
<h1>Editing homespace</h1>

<%= render 'form' %>

<%= link_to 'Show', @homespace %> |
<%= link_to 'Back', homespaces_path %>

app/views/homespaces/index.html.erb
<h1>Listing homespaces</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Partner</th>
      <th>Post ids</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @homespaces.each do |homespace| %>
      <tr>
        <td><%= homespace.user_id %></td>
        <td><%= homespace.partner_id %></td>
        <td><%= homespace.post_ids %></td>
        <td><%= link_to 'Show', homespace %></td>
        <td><%= link_to 'Edit', edit_homespace_path(homespace) %></td>
        <td><%= link_to 'Destroy', homespace, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Homespace', new_homespace_path %>

app/views/homespaces/new.html.erb
<h1>New homespace</h1>

<%= render 'form' %>

<%= link_to 'Back', homespaces_path %>

app/views/homespaces/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @homespace.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @homespace.user.username %>
</p>

<p>
  <strong>Partner:</strong>
  <%= @homespace.partner.username %>
</p>

<p>
  <strong>Posts:</strong>
  <ul>
  <% @homespace.posts.each do |post| %>
    <li><%= link_to post.title, post%></li>
  <% end %>
  </ul>
</p>


<%= link_to 'Edit', edit_homespace_path(@homespace) %> |
<%= link_to 'Back', homespaces_path %>