config/routes.rb
Theverb::Application.routes.draw do
  resources :posts

  resources :homespaces

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks", :registrations => "users/registrations" }
  
  get "/auth/:provider/callback" => "sessions#create"
  
  resources :users
  
  devise_scope :user do
    get "/login" => "devise/sessions#new"
    get "/signup" => "devise/registrations#new"
    delete "/logout" => "devise/sessions#destroy"
  end
  
  

  
    authenticated :user do
      root :to => redirect("/posts"), :as => "authenticated_root"
    end
    
    root :to => redirect("/users")

  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Theverb</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Open+Sans:400,300" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
    <div class="banner">
        <% if user_signed_in? && @user_homespace != nil %>
            <h1><%= link_to "Homespace", homespace_path(@user_homespace) %></h1><h3>A place to share, organize, and do.</h3>
            <p>Want to add something? <%= link_to "Add a post here!", new_post_path %></p>
        <% else %>
            <h1>Homespace</h1><h3>A place to share, organize, and do.</h3>
        <% end %>
        <p class="notice"><%= notice %></p>                                                                                                                                                                                                         
        <p class="alert"><%= alert %></p> 
    </div>
        <%= yield %>
    <div class="banner"
        <% if can? :manage, :all %>
            <ul>
            	<li><%= link_to current_user.username, user_path(current_user) %>'s Dashboard (is <%= current_user.role %>):</li>
                <li><%= link_to "Edit my registration", edit_user_registration_path(current_user) %></li>
            	<li> <%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li> 
        
            </ul>
            <% elsif user_signed_in? %>
            <ul>
            	<li><%= link_to current_user.username, user_path(current_user) %>'s Dashboard (is <%= current_user.role %>): </li>
                <li><%= link_to "Edit my registration", edit_user_registration_path(current_user) %></li>
            	<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            </ul>
            <% else %>
            <%= link_to 'Login', login_url %> | <%= link_to 'Sign Up', new_user_registration_url %>
        
        <% end %>
    </div>    
</div>
</body>
</html>